[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
    "CDLA-Permissive-2.0",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
skip = [
    # Known safe duplicates due to dependency tree requirements
    { name = "getrandom", version = "=0.2.16" },
    { name = "hashbrown", version = "=0.14.5" },
    { name = "wasi", version = "=0.11.1+wasi-snapshot-preview1" },
    { name = "windows-sys", version = "=0.52.0" },
    { name = "windows-sys", version = "=0.59.0" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"