name: ✨ Feature Request
description: Suggest a new feature for the VirusTotal Rust SDK
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: ["ThreatFlux"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I have also considered...
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New VirusTotal API endpoint support
        - Existing API enhancement
        - Developer experience improvement
        - Performance optimization
        - Security enhancement
        - Documentation improvement
        - MCP (Model Context Protocol) feature
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: api-example
    attributes:
      label: API Design Example
      description: If applicable, show what the API might look like
      render: rust
      placeholder: |
        // Example of how the feature might be used
        let client = ClientBuilder::new()
            .api_key("key")
            .build()?;
        
        let result = client.new_feature().some_method().await?;
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: I need this feature because...
    validations:
      required: true

  - type: checkboxes
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes to the public API
        - label: This feature can be implemented without breaking changes
        - label: I'm not sure about the impact on existing APIs

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation
        - label: I would prefer someone else implement this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
        - label: I have considered how this feature might affect existing users
          required: true