name: ❓ Question
description: Ask a question about the VirusTotal Rust SDK
title: "[QUESTION] "
labels: ["question", "needs-triage"]
assignees: ["ThreatFlux"]

body:
  - type: markdown
    attributes:
      value: |
        Have a question about using the VirusTotal Rust SDK? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What area does your question relate to?
      options:
        - API Usage
        - Authentication
        - Rate Limiting
        - Error Handling
        - MCP (Model Context Protocol)
        - Examples and Documentation
        - Installation and Setup
        - Performance and Optimization
        - Security Best Practices
        - Feature Availability
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context for your question
      placeholder: I'm trying to... and I want to understand...
    validations:
      required: false

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample (if applicable)
      description: If your question relates to specific code, please share it
      render: rust
      placeholder: |
        use virustotal_rs::*;
        
        // Your code here
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: SDK Version
      description: What version of virustotal-rs are you using?
      placeholder: "0.1.0"
    validations:
      required: false

  - type: dropdown
    id: api-tier
    attributes:
      label: VirusTotal API Tier
      description: What VirusTotal API tier are you using?
      options:
        - Public API
        - Premium API
        - Not applicable
        - I don't know
    validations:
      required: false

  - type: textarea
    id: attempted-solutions
    attributes:
      label: What have you tried?
      description: Describe any solutions you've already attempted
      placeholder: I have tried...
    validations:
      required: false

  - type: checkboxes
    id: documentation
    attributes:
      label: Documentation
      description: Have you checked the available documentation?
      options:
        - label: I have read the README
        - label: I have checked the API documentation
        - label: I have looked at the examples
        - label: I have searched existing issues and discussions

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Any additional details...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing questions and issues before asking
          required: true
        - label: My question is specific to the VirusTotal Rust SDK
          required: true