name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_HOME: ${{ github.workspace }}/.cargo
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: Test Suite
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta]
        include:
          - os: ubuntu-latest
            rust: 1.85.0  # MSRV
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Free disk space
      if: runner.os == 'Linux'
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/share/swift
        sudo apt-get clean
        echo "Disk space after cleanup:"
        df -h
        
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/debug/deps
          target/debug/build
        key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.rust }}-
          ${{ runner.os }}-cargo-

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev

    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install openssl pkg-config

    - name: Check formatting
      if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
      run: cargo fmt --all -- --check

    - name: Run clippy
      if: matrix.rust == 'stable'
      run: cargo clippy --all-features --all-targets -- -D warnings

    - name: Build
      run: |
        if [[ "${{ matrix.rust }}" == "beta" ]]; then
          echo "Using single-threaded build for beta toolchain to avoid memory issues"
          cargo build --all-features --verbose -j 1
        else
          cargo build --all-features --verbose
        fi
      shell: bash

    - name: Run tests
      run: |
        if [[ "${{ matrix.rust }}" == "beta" ]]; then
          echo "Using single-threaded test build for beta toolchain to avoid memory issues"
          cargo test --all-features --verbose -j 1
        else
          cargo test --all-features --verbose
        fi
      shell: bash

    - name: Test without features
      run: cargo test --no-default-features --verbose

    - name: Debug environment
      if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
      run: |
        echo "Environment Debug Information:"
        echo "Rust version: $(rustc --version)"
        echo "Cargo version: $(cargo --version)"
        echo "Available disk space:"
        df -h
        echo "Memory info:"
        free -h || true
        echo "CPU info:"
        nproc
    
    - name: Test with MCP features
      run: |
        echo "Testing MCP features individually..."
        cargo test --features mcp --verbose
        echo "Testing MCP JWT features..."
        cargo test --features mcp-jwt --verbose
        echo "Testing MCP OAuth features..."
        cargo test --features mcp-oauth --verbose

    - name: Build examples
      run: |
        if [[ "${{ matrix.rust }}" == "beta" ]]; then
          echo "Using single-threaded build for beta toolchain to avoid memory issues"
          cargo build --examples --all-features -j 1
        else
          cargo build --examples --all-features
        fi
      shell: bash
        
    - name: Test documentation
      if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
      run: cargo test --doc --all-features
      
    - name: Clean up build artifacts
      if: always() && runner.os == 'Linux'
      run: |
        echo "Cleaning up build artifacts to save disk space..."
        # Remove large intermediate files
        find target -name "*.rlib" -type f -delete || true
        find target -name "*.rmeta" -type f -delete || true
        find target/debug -name "*.d" -type f -delete || true
        # Clean doc builds
        rm -rf target/doc || true
        # Clean test executables (keep deps for cache)
        find target/debug -maxdepth 1 -type f -executable -delete || true
        echo "Disk space after cleanup:"
        df -h

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      with:
        components: llvm-tools-preview

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-llvm-cov

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-coverage-${{ hashFiles('**/Cargo.lock') }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev

    - name: Generate coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
      with:
        files: lcov.info
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.lock') }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev

    - name: Check documentation
      run: |
        # Create docs header for CI
        cat > docs-header.html << 'EOF'
        <style>
          .sidebar { width: 250px; }
          .content { margin-left: 250px; }
        </style>
        EOF
        RUSTDOCFLAGS="-D warnings --html-in-header docs-header.html" cargo doc --all-features --no-deps --document-private-items

    - name: Test doc examples
      run: cargo test --doc --all-features

  feature-combinations:
    name: Feature Combinations
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable

    - name: Install cargo-hack
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-hack-${{ hashFiles('**/Cargo.lock') }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev

    - name: Check feature combinations
      run: cargo hack check --feature-powerset --depth 2 --all-targets

  benchmark:
    name: Benchmarks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev

    - name: Run benchmarks
      run: cargo bench --all-features || echo "No benchmarks found"